name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cp .env.example .env
          echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for container to be ready and install dev dependencies
        run: |
          sleep 10
          docker exec steam-app composer install --dev

      - name: Run code style check (Pint)
        run: docker exec steam-app composer format

      - name: Run static analysis (PHPStan) [optional]
        run: docker exec steam-app composer analyse
        continue-on-error: true   # не ломает пайплайн, если ошибки есть

      - name: add an exception for this directory for git
        run: docker exec steam-app git config --global --add safe.directory /var/www/html

      - name: Run tests (Pest)
        run: docker exec steam-app composer test

      - name: Shutdown containers
        if: always()
        run: docker compose down